module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_form_alter: 0
  block_style_plugins: 0
  bootstrap_layout_builder: 0
  bootstrap_styles: 0
  breakpoint: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  color_field: 0
  comment: 0
  components: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  gin_login: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  language: 0
  layout_builder: 0
  layout_builder_blocks: 0
  layout_builder_component_attributes: 0
  layout_builder_modal: 0
  layout_discovery: 0
  layout_library: 0
  lb_claro: 0
  lb_direct_add: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_link_content: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  search: 0
  shortcut: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_anti_flicker: 0
  tour: 0
  twig_tweak: 0
  update: 0
  user: 0
  views_ui: 0
  ds: 1
  pathauto: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  bartik: 0
  seven: 0
  claro: 0
  gin: 0
  radix: 0
  drupalcol: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: es
